// Generated by jextract

package darknet;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct DarknetBox {
 *     float x;
 *     float y;
 *     float w;
 *     float h;
 * } box
 * }
 */
public class box extends DarknetBox {

    box() {
        // Should not be called directly
    }
}

