// Generated by jextract

package darknet;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct DarknetDetection {
 *     DarknetBox bbox;
 *     int classes;
 *     int best_class_idx;
 *     float *prob;
 *     float *mask;
 *     float objectness;
 *     int sort_class;
 *     float *uc;
 *     int points;
 *     float *embeddings;
 *     int embedding_size;
 *     float sim;
 *     int track_id;
 * } detection
 * }
 */
public class detection extends DarknetDetection {

    detection() {
        // Should not be called directly
    }
}

