// Generated by jextract

package darknet;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct DarknetImage {
 *     int w;
 *     int h;
 *     int c;
 *     float *data;
 * } image
 * }
 */
public class image extends DarknetImage {

    image() {
        // Should not be called directly
    }
}

